import 'package:who_mobile_project/general/models/base_dropdown_item.dart';

class ProvinceItem extends BaseDropDownItemModel {
  final String code;
  final String fullName;

  ProvinceItem({required this.code, required this.fullName})
    : super(id: code, name: fullName);

  @override
  String get displayName => fullName;

  static List<ProvinceItem> getAllProvinces() {
    return [
      ProvinceItem(code: 'AG', fullName: 'Agrigento'),
      ProvinceItem(code: 'AL', fullName: 'Alessandria'),
      ProvinceItem(code: 'AN', fullName: 'Ancona'),
      ProvinceItem(code: 'AO', fullName: 'Aosta'),
      ProvinceItem(code: 'AR', fullName: 'Arezzo'),
      ProvinceItem(code: 'AP', fullName: 'Ascoli Piceno'),
      ProvinceItem(code: 'AT', fullName: 'Asti'),
      ProvinceItem(code: 'AV', fullName: 'Avellino'),
      ProvinceItem(code: 'BA', fullName: 'Bari'),
      ProvinceItem(code: 'BT', fullName: 'Barletta-Andria-Trani'),
      ProvinceItem(code: 'BL', fullName: 'Belluno'),
      ProvinceItem(code: 'BN', fullName: 'Benevento'),
      ProvinceItem(code: 'BG', fullName: 'Bergamo'),
      ProvinceItem(code: 'BI', fullName: 'Biella'),
      ProvinceItem(code: 'BO', fullName: 'Bologna'),
      ProvinceItem(code: 'BZ', fullName: 'Bolzano'),
      ProvinceItem(code: 'BS', fullName: 'Brescia'),
      ProvinceItem(code: 'BR', fullName: 'Brindisi'),
      ProvinceItem(code: 'CA', fullName: 'Cagliari'),
      ProvinceItem(code: 'CL', fullName: 'Caltanissetta'),
      ProvinceItem(code: 'CB', fullName: 'Campobasso'),
      ProvinceItem(code: 'CE', fullName: 'Caserta'),
      ProvinceItem(code: 'CT', fullName: 'Catania'),
      ProvinceItem(code: 'CZ', fullName: 'Catanzaro'),
      ProvinceItem(code: 'CH', fullName: 'Chieti'),
      ProvinceItem(code: 'CO', fullName: 'Como'),
      ProvinceItem(code: 'CS', fullName: 'Cosenza'),
      ProvinceItem(code: 'CR', fullName: 'Cremona'),
      ProvinceItem(code: 'KR', fullName: 'Crotone'),
      ProvinceItem(code: 'CN', fullName: 'Cuneo'),
      ProvinceItem(code: 'EN', fullName: 'Enna'),
      ProvinceItem(code: 'FM', fullName: 'Fermo'),
      ProvinceItem(code: 'FE', fullName: 'Ferrara'),
      ProvinceItem(code: 'FI', fullName: 'Firenze'),
      ProvinceItem(code: 'FG', fullName: 'Foggia'),
      ProvinceItem(code: 'FC', fullName: 'Forlì-Cesena'),
      ProvinceItem(code: 'FR', fullName: 'Frosinone'),
      ProvinceItem(code: 'GE', fullName: 'Genova'),
      ProvinceItem(code: 'GO', fullName: 'Gorizia'),
      ProvinceItem(code: 'GR', fullName: 'Grosseto'),
      ProvinceItem(code: 'IM', fullName: 'Imperia'),
      ProvinceItem(code: 'IS', fullName: 'Isernia'),
      ProvinceItem(code: 'SP', fullName: 'La Spezia'),
      ProvinceItem(code: 'AQ', fullName: "L'Aquila"),
      ProvinceItem(code: 'LT', fullName: 'Latina'),
      ProvinceItem(code: 'LE', fullName: 'Lecce'),
      ProvinceItem(code: 'LC', fullName: 'Lecco'),
      ProvinceItem(code: 'LI', fullName: 'Livorno'),
      ProvinceItem(code: 'LO', fullName: 'Lodi'),
      ProvinceItem(code: 'LU', fullName: 'Lucca'),
      ProvinceItem(code: 'MC', fullName: 'Macerata'),
      ProvinceItem(code: 'MN', fullName: 'Mantova'),
      ProvinceItem(code: 'MS', fullName: 'Massa-Carrara'),
      ProvinceItem(code: 'MT', fullName: 'Matera'),
      ProvinceItem(code: 'ME', fullName: 'Messina'),
      ProvinceItem(code: 'MI', fullName: 'Milano'),
      ProvinceItem(code: 'MO', fullName: 'Modena'),
      ProvinceItem(code: 'MB', fullName: 'Monza e Brianza'),
      ProvinceItem(code: 'NA', fullName: 'Napoli'),
      ProvinceItem(code: 'NO', fullName: 'Novara'),
      ProvinceItem(code: 'NU', fullName: 'Nuoro'),
      ProvinceItem(code: 'OR', fullName: 'Oristano'),
      ProvinceItem(code: 'PD', fullName: 'Padova'),
      ProvinceItem(code: 'PA', fullName: 'Palermo'),
      ProvinceItem(code: 'PR', fullName: 'Parma'),
      ProvinceItem(code: 'PV', fullName: 'Pavia'),
      ProvinceItem(code: 'PG', fullName: 'Perugia'),
      ProvinceItem(code: 'PE', fullName: 'Pescara'),
      ProvinceItem(code: 'PC', fullName: 'Piacenza'),
      ProvinceItem(code: 'PI', fullName: 'Pisa'),
      ProvinceItem(code: 'PT', fullName: 'Pistoia'),
      ProvinceItem(code: 'PN', fullName: 'Pordenone'),
      ProvinceItem(code: 'PZ', fullName: 'Potenza'),
      ProvinceItem(code: 'PO', fullName: 'Prato'),
      ProvinceItem(code: 'RG', fullName: 'Ragusa'),
      ProvinceItem(code: 'RA', fullName: 'Ravenna'),
      ProvinceItem(code: 'RC', fullName: 'Reggio Calabria'),
      ProvinceItem(code: 'RE', fullName: 'Reggio Emilia'),
      ProvinceItem(code: 'RI', fullName: 'Rieti'),
      ProvinceItem(code: 'RN', fullName: 'Rimini'),
      ProvinceItem(code: 'RM', fullName: 'Roma'),
      ProvinceItem(code: 'RO', fullName: 'Rovigo'),
      ProvinceItem(code: 'SA', fullName: 'Salerno'),
      ProvinceItem(code: 'SS', fullName: 'Sassari'),
      ProvinceItem(code: 'SV', fullName: 'Savona'),
      ProvinceItem(code: 'SI', fullName: 'Siena'),
      ProvinceItem(code: 'SR', fullName: 'Siracusa'),
      ProvinceItem(code: 'SO', fullName: 'Sondrio'),
      ProvinceItem(code: 'TA', fullName: 'Taranto'),
      ProvinceItem(code: 'TE', fullName: 'Teramo'),
      ProvinceItem(code: 'TR', fullName: 'Terni'),
      ProvinceItem(code: 'TO', fullName: 'Torino'),
      ProvinceItem(code: 'TP', fullName: 'Trapani'),
      ProvinceItem(code: 'TN', fullName: 'Trento'),
      ProvinceItem(code: 'TV', fullName: 'Treviso'),
      ProvinceItem(code: 'TS', fullName: 'Trieste'),
      ProvinceItem(code: 'UD', fullName: 'Udine'),
      ProvinceItem(code: 'VA', fullName: 'Varese'),
      ProvinceItem(code: 'VE', fullName: 'Venezia'),
      ProvinceItem(code: 'VB', fullName: 'Verbano-Cusio-Ossola'),
      ProvinceItem(code: 'VC', fullName: 'Vercelli'),
      ProvinceItem(code: 'VR', fullName: 'Verona'),
      ProvinceItem(code: 'VV', fullName: 'Vibo Valentia'),
      ProvinceItem(code: 'VI', fullName: 'Vicenza'),
      ProvinceItem(code: 'VT', fullName: 'Viterbo'),
    ];
  }
}
